### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'materialNodetrees'

### ISSUE THREAD

**Issue by LichenSymbiont** [dertom95/Urho3D-Blender#6]
```
Traceback (most recent call last):
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/__init__.py", line 1582, in invoke
    return self.execute(context)
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/__init__.py", line 1578, in execute
    ExecuteAddon(context, not bpy.context.scene.urho_exportsettings.showLog )
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/__init__.py", line 2892, in ExecuteAddon
    ExecuteUrhoExport(context)
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/__init__.py", line 2740, in ExecuteUrhoExport
    Scan(context, tDataList, settings.errorsMem, tOptions)
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/decompose.py", line 2608, in Scan
    DecomposeMesh(scene, obj, tData, tOptions, errorsMem,obj.lodsetID>0)
  File "/home/user/.config/blender/2.80/scripts/addons/Urho3D-Blender-master/decompose.py", line 1935, in DecomposeMesh
    print("CHECK: %s %s idx:%s" % (hasattr(mesh,"materialNodetrees"), len(mesh.materialNodetrees),materialIndex))
AttributeError: 'Mesh' object has no attribute 'materialNodetrees'

location: <unknown location>:-1
```

This is from Blender 17:2.80-7 on Arch Linux. I have watched the install video, and it was so straightforward. But alas. I've used the old addon in Blender 2.77 with no problems.

Also thank you so much for making the addon! I'd be making my own modeling tool in Urho or something if this didn't exist ^^

Edit: well, I found the 2.8 branch of the official version, and it seems to work like usual! So that's good enough for me!

**Comment by MzaxnaV** [comment]
> Edit: well, I found the 2.8 branch of the official version, and it seems to work like usual! So that's good enough for me!

I also have the same problem with the add-on on openSUSE Tumbleweed. What did you mean when you said you found the 2.8 branch of the official version, the only two branches i found aside from master are 2.7 and custom-renderer-test? Would you please share the link to it or explain in detail what worked for you?

**Comment by dertom95** [comment]
I guess you didn't enabled addon_jsonnode-blender addon.....
